### ISSUE TITLE
Scene files

### ISSUE THREAD

**Issue by knightcrawler25** [brickray/gpu-pathtracer#1]
Hey, Could you share the json scene files corresponding to the screenshots?

**Comment by brickray** [comment]
Hey, The scenes I use are almost all from here. https://benedikt-bitterli.me/resources/

**Comment by knightcrawler25** [comment]
Ah, but since the tungsten scene format is slightly different from the one you are using so I felt it would be easier for me to use if I had the scene files corresponding to your renderer. Thanks for adding them :)

**Comment by brickray** [comment]
I have added them now

**Comment by knightcrawler25** [comment]
Thanks! It works beautifully :)
